apiVersion: v2
name: mychart
description: Application chart that uses the mylib library chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mylib
    version: "0.1.0"
    repository: "file://../mylib"
