apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-project
  namespace: argocd
spec:
  description: "Team project for developer access"
  sourceRepos:
    - 'https://github.com/argoproj/argocd-example-apps.git'
  destinations:
    - namespace: rbac-lab
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
