#!/bin/bash
set -e

echo "============================================"
echo "Lab 13: Self-Hosted Runner Autoscaling (ARC)"
echo "============================================"
echo ""
echo "This lab simulates a broken Actions Runner Controller"
echo "deployment where jobs hang and runners don't scale."
echo ""
echo "Scenario: Your org moved to self-hosted runners with ARC"
echo "for cost savings, but jobs queue indefinitely. Runners"
echo "register but never pick up jobs, DinD is broken, and"
echo "stale workspaces corrupt builds."
echo ""
echo "Files to investigate:"
echo "  1. .github/workflows/broken-runner.yml   (workflow using runners)"
echo "  2. runner-deployment.yaml                (ARC HRA configuration)"
echo ""
echo "There are 5 bugs to find:"
echo "  - Runner label mismatch (runs-on vs registered labels)"
echo "  - HRA minReplicas=0 with excessive scale-up delay"
echo "  - Runner not ephemeral (stale workspace)"
echo "  - DinD (dockerdWithinRunnerContainer) missing volumes"
echo "  - Registration token expired (hardcoded)"
echo ""
echo "============================================"
echo "NOTE: This is a configuration review lab."
echo "If you have a k8s cluster with ARC, you can deploy:"
echo "  kubectl apply -f runner-deployment.yaml"
echo "============================================"
echo ""
echo "Start by examining:"
echo "  cat .github/workflows/broken-runner.yml"
echo "  cat runner-deployment.yaml"
