replicaCount: 2

image:
  repository: nginx
  tag: "1.24"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# VPA will mutate these values on the live object
vpa:
  enabled: true
  updateMode: "Auto"

# Istio injection
istio:
  inject: true
