version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8443:443"
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - lab02-network

networks:
  lab02-network:
    driver: bridge
