apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: mychart
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      - name: istio-proxy
        image: istio/proxyv2:1.19.0
        ports:
          - containerPort: 15090
            name: http-envoy-prom
