#!/bin/bash
set -e

echo "============================================"
echo "  Lab 13: Pipeline Replay Divergence"
echo "  Difficulty: ⭐⭐⭐⭐⭐ Expert"
echo "============================================"
echo ""
echo "Scenario: Pipeline replayed from Blue Ocean behaves differently"
echo "than SCM-triggered runs. Environment variables are missing,"
echo "parameters are stale, and shared library changes aren't picked up."
echo ""

cd "$(dirname "$0")"

echo "This lab requires a running Jenkins instance with:"
echo "  1. A pipeline job configured with SCM (Git)"
echo "  2. Blue Ocean plugin installed"
echo "  3. A shared library configured"
echo ""
echo "To set up manually:"
echo "  1. Start Jenkins: docker run -d -p 8080:8080 jenkins/jenkins:lts"
echo "  2. Install Blue Ocean plugin"
echo "  3. Create a Multibranch Pipeline pointing to this repo"
echo "  4. Configure shared library from vars/ directory"
echo "  5. Trigger a build from SCM → observe success"
echo "  6. Use 'Replay' from Blue Ocean → observe different behavior"
echo ""
echo "Quick setup with docker compose:"
echo "  docker run -d --name jenkins-replay-lab \\"
echo "    -p 8080:8080 -p 50000:50000 \\"
echo "    -v \$(pwd):/var/jenkins_home/workspace/replay-lab \\"
echo "    -e JAVA_OPTS='-Djenkins.install.runSetupWizard=false' \\"
echo "    jenkins/jenkins:2.426.1-lts"
echo ""
echo "============================================"
echo "  Lab deployed!"
echo "============================================"
echo ""
echo "Your task: Identify WHY the pipeline behaves differently on replay"
echo "and fix the Jenkinsfile + shared library to work correctly in BOTH"
echo "SCM-triggered AND replayed scenarios."
echo ""
echo "Issues to investigate:"
echo "  1. @Library version resolution differences"
echo "  2. params.* defaultValue vs cached values"
echo "  3. env.BRANCH_NAME empty on replay"
echo "  4. stash/unstash unavailability"
echo "  5. currentBuild.changeSets empty"
echo ""
