#!/bin/bash
set -e

echo "============================================"
echo "Lab 11: GitHub Actions OIDC Token Federation"
echo "============================================"
echo ""
echo "This lab simulates a broken OIDC federation between"
echo "GitHub Actions and AWS IAM."
echo ""
echo "Scenario: Your workflow uses OIDC to assume an AWS role"
echo "but every run fails with AccessDenied."
echo ""
echo "Files to investigate:"
echo "  1. .github/workflows/broken-oidc.yml  (GitHub Actions workflow)"
echo "  2. terraform/oidc-role.tf             (IAM role trust policy)"
echo ""
echo "There are 5 bugs to find:"
echo "  - Wrong OIDC audience in trust policy"
echo "  - Subject claim mismatch (wrong repo/owner)"
echo "  - Incorrect condition operator (StringEquals vs StringLike)"
echo "  - Missing id-token: write permission in workflow"
echo "  - Role session duration exceeds MaxSessionDuration"
echo ""
echo "============================================"
echo "NOTE: This is a configuration review lab."
echo "No cloud resources are deployed."
echo "Examine the files and identify all issues."
echo "============================================"
echo ""
echo "Start by examining:"
echo "  cat .github/workflows/broken-oidc.yml"
echo "  cat terraform/oidc-role.tf"
