#!/bin/bash
set -e

echo "============================================"
echo "Lab 12: Reusable Workflow Inputs/Secrets/Outputs"
echo "============================================"
echo ""
echo "This lab simulates a broken GitHub Actions reusable"
echo "workflow integration with input/output mismatches."
echo ""
echo "Scenario: After refactoring to reusable workflows,"
echo "deployments fail due to type mismatches, missing"
echo "secrets, and broken output chains."
echo ""
echo "Files to investigate:"
echo "  1. .github/workflows/caller.yml          (caller workflow)"
echo "  2. .github/workflows/reusable-deploy.yml (reusable workflow)"
echo ""
echo "There are 5 bugs to find:"
echo "  - secrets: inherit missing (secrets not passed)"
echo "  - Input type mismatch (boolean vs string)"
echo "  - Output variable not exposed from job to workflow level"
echo "  - env context not available in reusable workflow"
echo "  - needs context references wrong job ID"
echo ""
echo "============================================"
echo "NOTE: This is a configuration review lab."
echo "No resources are deployed."
echo "Examine the files and identify all issues."
echo "============================================"
echo ""
echo "Start by examining:"
echo "  cat .github/workflows/caller.yml"
echo "  cat .github/workflows/reusable-deploy.yml"
