apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mychart
  labels:
    app: {{ .Release.Name }}-mychart
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mychart
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mychart
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            {{- range $key, $value := .Values.labels }}
            - name: LABEL_{{ $key | upper }}
              value: {{ .Values.image.tag }}
            {{- end }}
